### ISSUE TITLE
Segfault when initializing Caffe::Net

### ISSUE THREAD

**Issue by geovations** [NVIDIA/caffe#273]
I'm having an issue when using nv-caffe with CUDNN.  When I include CUDNN (5.0 or 5.1.5) in my nv-caffe build, I get a segmentation fault during Caffe::Net initialization. This does not happen when I exclude CUDNN, or when I use the BVLC fork.  My setup is using the 0.15 branch with CUDNN 5.1.5, Boost 1.6.1, OpenCV 3.1, all compiled with CUDA 8.  This exact error also happens when using CUDA 7.5 with a similar setup.

The call stack is:
```(gdb) backtrace
#0  0x00000000005b9bac in boost::detail::atomic_exchange_and_add (pw=0x9, 
    dv=-1)
    at /usr/local/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:50
#1  0x00000000005b9bd9 in boost::detail::sp_counted_base::release (this=0x1)
    at /usr/local/include/boost/smart_ptr/detail/sp_counted_base_gcc_x86.hpp:144
#2  0x00000000005b9c8d in boost::detail::shared_count::~shared_count (
    this=0x7fffffffc668, __in_chrg=<optimized out>)
    at /usr/local/include/boost/smart_ptr/detail/shared_count.hpp:473
#3  0x00007ffff766bd5e in boost::shared_ptr<caffe::Caffe::RNG>::~shared_ptr (
    this=0x7fffffffc660, __in_chrg=<optimized out>)
    at /usr/local/include/boost/smart_ptr/shared_ptr.hpp:336
#4  0x00007ffff766c87b in boost::shared_ptr<caffe::Caffe::RNG>::reset<caffe::Caffe::RNG> (this=0xaaf5d8, p=0x1733d340)
    at /usr/local/include/boost/smart_ptr/shared_ptr.hpp:665
#5  0x00007ffff7812f17 in caffe::Caffe::rng_stream ()
    at /home/jwhite/Downloads/nv-caffe/include/caffe/common.hpp:130
#6  0x00007ffff7813368 in caffe::caffe_rng ()
    at /home/jwhite/Downloads/nv-caffe/include/caffe/util/rng.hpp:17
#7  0x00007ffff7813d34 in caffe::caffe_rng_uniform<float> (n=500, 
    a=-0.346410155, b=0.346410155, r=0x203960000)
    at /home/jwhite/Downloads/nv-caffe/src/caffe/util/math_functions.cpp:253
#8  0x00007ffff76bf8c8 in caffe::XavierFiller<float>::Fill (this=0x17336b30, 
    blob=0x17332bd0)
    at /home/jwhite/Downloads/nv-caffe/include/caffe/filler.hpp:296
#9  0x00007ffff76b1f96 in caffe::BaseConvolutionLayer<float>::LayerSetUp (
    this=0x173444c0, bottom=std::vector of length 1, capacity 1 = {...}, 
    top=std::vector of length 1, capacity 1 = {...})
    at /home/jwhite/Downloads/nv-caffe/src/caffe/layers/base_conv_layer.cpp:170
#10 0x00007ffff76d7515 in caffe::CuDNNConvolutionLayer<float>::LayerSetUp (
    this=0x173444c0, bottom=std::vector of length 1, capacity 1 = {...}, 
    top=std::vector of length 1, capacity 1 = {...})
    at /home/jwhite/Downloads/nv-caffe/src/caffe/layers/cudnn_conv_layer.cpp:20
#11 0x00007ffff768c5d2 in caffe::Layer<float>::SetUp (this=0x173444c0, 
    bottom=std::vector of length 1, capacity 1 = {...}, 
    top=std::vector of length 1, capacity 1 = {...})
    at /home/jwhite/Downloads/nv-caffe/include/caffe/layer.hpp:71
#12 0x00007ffff7789e88 in caffe::Net<float>::Init (this=0x17342440, 
    in_param=...) at /home/jwhite/Downloads/nv-caffe/src/caffe/net.cpp:142
#13 0x00007ffff7788161 in caffe::Net<float>::Net (this=0x17342440, param=..., 
    root_net=0x0) at /home/jwhite/Downloads/nv-caffe/src/caffe/net.cpp:27
```

**Comment by drnikolaev** [comment]
Please update to 0.16
