### ISSUE TITLE
Segmentation fault in caffe_rng_gaussian

### ISSUE THREAD

**Issue by Bidski** [NVIDIA/caffe#300]
I am trying to run the cpp-classification example but keep receiving the following segmentation fault
```
0x00007ffff6f60236 in void caffe::caffe_rng_gaussian<float>(int, float, float, float*) () from /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
(gdb) bt
#0  0x00007ffff6f60236 in void caffe::caffe_rng_gaussian<float>(int, float, float, float*) () at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#1  0x00007ffff6de4187 in caffe::GaussianFiller<float>::Fill(caffe::Blob<float>*) () at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#2  0x00007ffff6de68a8 in caffe::BaseConvolutionLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) () at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#3  0x00007ffff6e0d1d6 in caffe::CuDNNConvolutionLayer<float>::LayerSetUp(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) () at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#4  0x00007ffff6f006e4 in caffe::Net<float>::Init(caffe::NetParameter const&) () at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#5  0x00007ffff6f0237d in caffe::Net<float>::Net(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Phase, caffe::Net<float> const*) ()
    at /home/bidski/Projects/nvidia/caffe/build/lib/libcaffe-nv.so.0.15
#6  0x0000000000410168 in Classifier::Classifier(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x7fffffffdcb0, model_file="/home/bidski/Projects/nvidia/DIGITS/digits/jobs/20170320-173909-4f5a/deploy.prototxt", trained_file="/home/bidski/Projects/nvidia/DIGITS/digits/jobs/20170320-173909-4f5a/snapshot_iter_249984.caffemodel", mean_file="/home/bidski/Projects/nvidia/DIGITS/digits/jobs/20170320-141524-bad6/mean.binaryproto", label_file="/home/bidski/ownCloud/GTSRB/labels.txt")
    at /home/bidski/Projects/4Tel/convnet/classification.cpp:51
#7  0x00000000004119fc in main(int, char**) (argc=6, argv=0x7fffffffdf08) at /home/bidski/Projects/4Tel/convnet/classification.cpp:263
```
Output from cmake (from building caffe-0.15)
```
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib64/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib64/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Found lmdb    (include: /usr/include, library: /usr/lib64/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib64/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib64/libsnappy.so)
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /opt/cuda/include, library: /opt/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- OpenCV found (/usr/local/share/OpenCV)
-- Found OpenBLAS libraries: /usr/lib64/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- NumPy ver. 1.12.1 found (include: /usr/lib/python2.7/site-packages/numpy/core/include)
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   python
-- Found NCCL (include: /opt/cuda/include, library: /opt/cuda/lib/libnccl.so)
-- Detected Doxygen OUTPUT_DIRECTORY: ./doxygen/
-- Found Git: /usr/bin/git (found version "2.12.1") 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   0.15.14
--   Git               :   v0.15.14-10-g6d723362-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Open)
--   Boost             :   Yes (ver. 1.63)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.2.0)
--   lmdb              :   Yes (ver. 0.9.19)
--   LevelDB           :   Yes (ver. 1.19)
--   Snappy            :   Yes (ver. 1.1.4)
--   OpenCV            :   Yes (ver. 2.4.13.2)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 5.1.10)
--   NCCL              :   Yes
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.13)
--   Libraries         :   /usr/lib64/libpython2.7.so (ver 2.7.13)
--   NumPy             :   /usr/lib/python2.7/site-packages/numpy/core/include (ver 1.12.1)
-- 
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.8.13)
--   config_file       :   /home/bidski/Projects/nvidia/caffe/.Doxyfile
-- 
-- Install:
--   Install path      :   /home/bidski/Projects/nvidia/caffe/build/install
```

**Comment by drnikolaev** [comment]
@Bidski Can't reproduce. May I have the command line you run please?

**Comment by Bidski** [comment]
With the upgrade to caffe-0.16 this issue no longer occurs.
