### ISSUE TITLE
Pretrained model from scripts/download_model_binary.py returns error: No route to host

### ISSUE THREAD

**Issue by GrabbenD** [NVIDIA/caffe#577]
Hey there!

We're in progress of migrating over from `BVLC/caffe` to `NVIDIA/caffe` for GPU compatibility with Tesla T4 but we've ran into an issue:
```
upgrade_proto.cpp:86] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /usr/src/up/app/pose/training/model/pose/test2.caffemodel
```

From our understanding we need to generate a new pretrained model with the script provided in: `scripts/download_model_binary.py models/bvlc_reference_caffenet` although this script returns error:
```
~/caffe# python2 scripts/download_model_binary.py models/bvlc_reference_caffenet
scripts/download_model_binary.py:36: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  frontmatter = yaml.load('\n'.join(lines[top + 1:bottom]))
Traceback (most recent call last):
  File "scripts/download_model_binary.py", line 73, in <module>
    frontmatter['caffemodel_url'], model_filename, reporthook)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 113] No route to host
```
How can we resolve this issue?

**Comment by GrabbenD** [comment]
This appears to be caused due to NVIDIA/Caffe being a few versions behind (0.17.3) while our project is built against Caffe 1.0.0 (latest as of today).
